name: 'seattle_weather_pipeline'
version: '1.0'
config-version: 2

profile: 'seattle_weather_pipeline'

source-paths: ["staging/models", "intermediate/models", "mart/models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  staging:
    + materialized: view
  intermediate:
    + materialized: table
  mart:
    + materialized: table 